[package]
name = "lx"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
lx-lib = { path = "../lx-lib" }

[dev-dependencies]
regex = { version = "1.11.1" }