[package]
name = "lx-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_builder = { version = "0.20.2"}
chrono = { version = "0.4.41" }
terminal_size = { version = "0.4.2" }

[dev-dependencies]
assert_fs = { version = "1.1.3" }